# NumPy Tutorial

Esse notebook foi criado como uma forma de revisar/aprender alguns conceitos básicos da biblioteca NumPy do Python. Segui [esse](https://www.youtube.com/watch?v=QUT1VHiLmmI&ab_channel=freeCodeCamp.org) tutorial.

***

## Introdução

- Por que o NumPy é mais rápido?
  - Tipagem forte e estática. Os tipos dentro de uma array não podem ser mudados, diferente do que acontece com listas (que são mutáveis). Por conta disso, a biblioteca usa menos bytes para fazer as mesmas operações.
  - Uso de memória contígua, isto é, os valores de uma array são guardados "lado a lado" dentro da memória do computador, o que torna as operações mais rápidas.

### Fundamentos

In [3]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [5]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [9]:
# Get Dimensions
print(a.ndim)
print(b.ndim)

# Get Shapes
print(a.shape)
print(b.shape)

# Data type
print(a.dtype)
print(b.dtype)

# Memory consumption
print(a.nbytes)
print(b.nbytes)

1
2
(3,)
(2, 3)
int32
float64
12
48


### Selecionando Trechos e Elementos (Array Slicing and Indexing)

In [10]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [13]:
# Get specific element [row, column]
print(a[1, 6])

# Or with negative notation
print(a[-1, -1])

14
14


In [15]:
# Get a specific row
print(a[0, :])

# Get specific column
print(a[:, 2])

[1 2 3 4 5 6 7]
[ 3 10]


In [21]:
# Using [row, start:end:step]
print(a[0, 0:5:2])

# Using [start:end:step, column]
print(a[::-1, :])

[1 3 5]
[[ 8  9 10 11 12 13 14]
 [ 1  2  3  4  5  6  7]]


In [22]:
# Changing elements
a[1, 5] = 20
print(a)

a[:, 5] = [8, 50]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  3  4  5  8  7]
 [ 8  9 10 11 12 50 14]]


In [31]:
# 3d array
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

# Get specific element (the tip is to work outside in)
print(b[0, 1, 1])

# Replace elements
b[0] = [[9, 10], [11, 12]]
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4
[[[ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]]]


### Diferentes Tipos de Arrays

#### Matrizes de 1 número só

In [42]:
# All-Zeros

# 1d array
print(np.zeros(5), end="\n\n")

# 2d array
print(np.zeros((3, 3)))


[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [43]:
# All 1s matrix
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [44]:
# Any other number
np.full((2, 2), 5)

array([[5, 5],
       [5, 5]])

#### Reproduzindo o formato de outras matrizes

In [45]:
# Reproducing the shape of other matrix
np.full_like(a, 2) # matrix a was defined prior in this notebook

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

#### Números Aleatórios

In [50]:
# Random decimal numbers
print(np.random.rand(4, 2))

# Random integers
print(np.random.randint(-100, 100, size=(3, 3)))

[[0.11576791 0.82880689]
 [0.72958807 0.08964552]
 [0.86293107 0.14365324]
 [0.2011232  0.21732445]]
[[-71  74 -21]
 [ 59  68  88]
 [ 23  62  17]]


#### Matriz Identidade

In [51]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Repetição

In [52]:
# Repeat an array

arr = np.array([[1, 2, 3]])
print(np.repeat(arr, 3, axis=0))

[[1 2 3]
 [1 2 3]
 [1 2 3]]


#### Exercício

Replique a matriz da foto usando os métodos ensinados até o momento.

![](assets/2022-03-25-11-15-51.png)


In [58]:
# Matriz de 1s
output = np.ones((5, 5), dtype='int32')

# Preenchendo 0s
output[1:4, 1:4] = np.zeros((3, 3), dtype='int32')

# Posicionando o 9
output[2, 2] = 9

output

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

### Cuidados ao copiar matrizes

Ao copiar uma matriz, você precisa dizer ao computador explicitamente o que está fazendo, caso contrário, o resultado pode diferir do esperado.

In [59]:
a = np.array([1, 2, 3])
b = a.copy()

b[0] = 100

print(a, b, sep='\n')

[1 2 3]
[100   2   3]


***

## Operações Matemáticas Básicas

In [11]:
arr = np.random.randint(-100, 110, size=10)
brr = np.random.randint(-100, 110, size=10)

print("arr: ", arr)
print("brr: ", brr)

print("\nOperações com uma array:")
# Adição
print("Array + 5: ", (arr + 5))

# Subtração
print("Array - 5: ", (arr - 5))

# Multiplicação
print("Array * 2: ", (arr * 2))

# Divisão
print("Array / 2: ", (arr / 2))

# Todas as operações acima também funcionam entre arrays do mesmo tamanho

print("\nOperações com duas arrays:")

print("arr + brr: ", (arr + brr))
print("arr - brr: ", (arr - brr))
print("arr * brr: ", (arr * brr))
print("arr / brr: ", (arr / brr))

print("\nAplicando funções em arrays:")

print("Seno (input em radianos): ", np.sin(arr))

arr:  [ 63  11  99   9 -81  60  68   6 -61 -66]
brr:  [-48 -35  -5 -53  76  28 -60  66  65 -90]

Operações com uma array:
Array + 5:  [ 68  16 104  14 -76  65  73  11 -56 -61]
Array - 5:  [ 58   6  94   4 -86  55  63   1 -66 -71]
Array * 2:  [ 126   22  198   18 -162  120  136   12 -122 -132]
Array / 2:  [ 31.5   5.5  49.5   4.5 -40.5  30.   34.    3.  -30.5 -33. ]

Operações com duas arrays:
arr + brr:  [  15  -24   94  -44   -5   88    8   72    4 -156]
arr - brr:  [ 111   46  104   62 -157   32  128  -60 -126   24]
arr * brr:  [-3024  -385  -495  -477 -6156  1680 -4080   396 -3965  5940]
arr / brr:  [ -1.3125      -0.31428571 -19.8         -0.16981132  -1.06578947
   2.14285714  -1.13333333   0.09090909  -0.93846154   0.73333333]

Aplicando funções em arrays:
Seno:  [ 0.1673557  -0.99999021 -0.99920683  0.41211849  0.62988799 -0.30481062
 -0.89792768 -0.2794155   0.96611777  0.02655115]


***

## Álgebra Linear

### Multiplicação de Matrizes

Dadas duas matrizes $A_{m \times n}$ e $B_{n \times p}$, podemos as multiplicá-las se o número de colunas da primeira $A_{m \times N}$ for igual ao número de linhas da segunda $B_{N \times p}$. Se essa condição for atendida, teremos como resultado uma matriz com o número de linhas de $A$ e o número de colunas de $B$:

$$
A_{m \times n} \cdot B_{n \times p} = C_{m \times p}
$$


In [21]:
a = np.random.randint(0, 11, size=(2, 4))
b = np.random.randint(0, 11, size=(4, 2))

print(a, b, sep="\n")

c = np.matmul(a, b)
print(c)
print(c.shape)

[[4 1 5 4]
 [1 6 0 2]]
[[ 9  6]
 [ 5 10]
 [ 6  9]
 [ 0  8]]
[[ 71 111]
 [ 39  82]]
(2, 2)


### Determinantes

[*"O determinante de uma matriz é uma “operação” que associa todas as matrizes quadradas a uma constante, ou seja, transformando-a em um escalar"*](https://www.infoescola.com/matematica/determinante-de-matrizes/). Conseguimos o determinante de uma matriz ao realizar o seguinte procedimento:

![](assets/2022-03-25-13-49-47.png)

Em código, fazemos o seguinte:

In [23]:
arr = np.random.randint(500, size=(2, 2))

print(arr)
print(np.linalg.det(arr))

[[302  56]
 [ 24 154]]
45163.999999999985


***

## Estatística

In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

### Máximos, mínimos e somas

In [26]:
# Geral
print(np.min(arr))
print(np.max(arr))

# Por linha
print(np.min(arr, axis=0))
print(np.max(arr, axis=0))

# Por colunas
print(np.min(arr, axis=1))
print(np.max(arr, axis=1))

# Soma de todos os elementos
print(np.sum(arr))

1
6
[1 2 3]
[4 5 6]
[1 4]
[3 6]
21


***

## Manipulando Formatos

In [27]:
# Reshape
# All values must be considered when rshaping an array

before = np.random.randint(10, size=(2, 4))
print(before)

after = before.reshape((4, 2))
print(after)

[[8 2 6 8]
 [2 4 0 9]]
[[8 2]
 [6 8]
 [2 4]
 [0 9]]


In [34]:
# Vertically stacking vectors
v1 = np.random.randint(10, size=(5))
v2 = np.random.randint(10, size=(5))

print(v1)
print(v2)
print(np.vstack([v1, v2]))

[2 4 8 1 8]
[3 2 0 0 4]
[[2 4 8 1 8]
 [3 2 0 0 4]]


In [33]:
# Horizontally stacking vectors
v1 = np.random.randint(10, size=(2, 5))
v2 = np.random.randint(10, size=(2, 5))

print(v1)
print(v2)
print(np.hstack([v1, v2]))

[[5 3 7 2 5]
 [7 4 7 8 8]]
[[5 8 2 6 7]
 [5 9 7 9 1]]
[[5 3 7 2 5 5 8 2 6 7]
 [7 4 7 8 8 5 9 7 9 1]]


***

## Exercícios

Dada a matriz e as partes de destaque:

![](assets/2022-03-25-14-40-13.png)

1. Como você selecionaria a parte destacada de azul?
2. Como você selecionaria a parte destacada de verde?
3. Como você selecionaria a parte destacada de vermelho?

In [50]:
v = np.arange(1, 31).reshape(6, 5)
print(v)

# Pergunta 1
print(v[2:4, :2])

# Pergunta 2
print(v[[0, 1, 2, 3], [1, 2, 3, 4]])

# Pergunta 3
print(v[[0, 4, 5], 3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]
